### ISSUE TITLE
API Error: version mismatch

### ISSUE THREAD

**Issue by prateekbhatt** [efficiosro/clj-ironmq#1]
Getting a bad request error. 

``` clojure
{:msg Version mismatch: unsupported API version '3', expected version '2', please upgrade your client. See http://docs.iron.io}
```

I inspected the reason, the version 3 api is 

`mq-aws-us-east-1-1.iron.io`

instead of 

`mq-aws-us-east-1.iron.io`

**Comment by featalion** [comment]
Hi, thanks for the notification. I see you have updated it already. I will test, merge, and release it ASAP. Thanks!
